export const cartActionTypes = {
  TOGGLE_CART_HIDDEN:"TOGGLE_CART_HIDDEN",
  ADD_ITEM:"ADD_ITEM",
  REMOVE_ITEM:"REMOVE_ITEM",
  DECREASE_ITEM_QUANTITY:"DECREASE_ITEM_QUANTITY",
  INCREASE_ITEM_QUANTITY:"INCREASE_ITEM_QUANTITY",
  CLEAR_CART_SUCCESS:"CLEAR_CART_SUCCESS"
}

